# Don't actually build.
build: off

environment:
  matrix:
   # Have to use number instead of LTS because of
   # https://help.appveyor.com/discussions/problems/9472-nodejs_version-stable-installs-the-wrong-version
   - nodejs_version: "LTS"
   - nodejs_version: "Stable"
   # will add 9 once canvas-prebuilt is supported

# Install scripts (runs after repo cloning).
install:
  - scripts\set-NPM_CONFIG_PREFIX.bat
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - yarn --version
  - yarn

# Post-install test scripts.
test_script:
  - yarn test
