environment:
  matrix:
   - nodejs_version: "LTS" # Have to use number instead of LTS because of http://help.appveyor.com/discussions/problems/9472-nodejs_version-stable-installs-the-wrong-version
   - nodejs_version: "Stable"
  # will add 9 once canvas-prebuilt is supported

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - npm install

# Post-install test scripts.
test_script:
  - npm test

# Don't actually build.
build: off
