# These are the different types of jobs run by Azure Pipelines:
#
# * Generic PRs
# * Changes in master
# * Dependabot PRs
# * Cron jobs to do a full analysis
jobs:

# Changes in master
- template: azure-pipelines/master.yml
  parameters:
    name: Linux_master
    vmImage: 'ubuntu 16.04'

- template: azure-pipelines/master.yml
  parameters:
    name: macOS_master
    vmImage: 'macOS-10.13'

- template: azure-pipelines/master.yml
  parameters:
    name: Windows_master
    vmImage: 'vs2017-win2016'

# Generic PRs
- template: azure-pipelines/prs.yml
  parameters:
    name: Linux_PR
    vmImage: 'ubuntu 16.04'

- template: azure-pipelines/prs.yml
  parameters:
    name: macOS_PR
    vmImage: 'macOS-10.13'

- template: azure-pipelines/prs.yml
  parameters:
    name: Windows_PR
    vmImage: 'vs2017-win2016'
