version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "all"
    ignored_updates:
      - match:
          dependency_name: "angular"
          version_requirement: ">1.4.9"
      - match:
          dependency_name: "jquery"
          version_requirement: ">2.1.4"
      - match:
          dependency_name: "@types/node"
          version_requirement: ">10.9.1"
      - match:
          dependency_name: "mime-db"
          version_requirement: ">1.35.0"
      - match:
          dependency_name: "proxyquire"
          version_requirement: ">2.0.0"

    version_requirement_updates: "auto"
