parameters:
  name: ''
  vmImage: ''
  condition: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
     node_8_x:
       node_version: 8.x
     node_10_x:
       node_version: 10.x
     node_11_x:
       node_version: 11.x
  steps:
  - template: worker.yml
  condition: ${{ parameters.condition }}
