# PRs
# Run latest version of node in all platforms
jobs:
  - template: latest-version.yml
    parameters:
        name: Linux_PR
        vmImage: 'ubuntu 16.04'
        condition: and(eq(variables['Build.Reason'], 'PullRequest'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/dependabot/')))

  - template: latest-version.yml
    parameters:
        name: macOS_PR
        vmImage: 'macOS-10.13'
        condition: and(eq(variables['Build.Reason'], 'PullRequest'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/dependabot/')))

  - template: latest-version.yml
    parameters:
        name: Windows_PR
        vmImage: 'vs2017-win2016'
        condition: and(eq(variables['Build.Reason'], 'PullRequest'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/dependabot/')))
