steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Update Chrome on Linux'
  - script: brew update && brew cask install google-chrome
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: 'Update Chrome on macOS'
  - script: |
      choco install googlechrome
      type C:\ProgramData\chocolatey\logs\chocolatey.log
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: 'Update Chrome on Windows'
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: 'Use Yarn 1.x'
    inputs:
      checkLatest: true
  - script: yarn
    displayName: 'Install dependencies'
  - script: yarn test
    displayName: 'Test'
